site_name: Learning Programming Languages
site_url: https://127.0.0.1
theme:
  name: material
  palette:
    primary: green
  features:
    - content.tooltips

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Install:
    - install/go.md
    - install/javascript.md
    - install/python.md
    - install/rust.md
  - Tools:
    - tools/index.md
    - Compile:
      - tools/compile/go.md
      - tools/compile/javascript.md
      - tools/compile/python.md
      - tools/compile/rust.md
    - Format:
      - tools/format/go.md
      - tools/format/javascript.md
      - tools/format/python.md
      - tools/format/rust.md
    - Debug:
      - tools/debug/go.md
      - tools/debug/javascript.md
      - tools/debug/python.md
      - tools/debug/rust.md
    - LSP:
      - tools/lsp/go.md
      - tools/lsp/javascript.md
      - tools/lsp/python.md
      - tools/lsp/rust.md
    - Package Manager:
      - tools/package_manager/index.md
      - Initialize:
        - tools/package_manager/initialize/go.md
        - tools/package_manager/initialize/python.md
        - tools/package_manager/initialize/rust.md
      - Add:
        - tools/package_manager/add/go.md
        - tools/package_manager/add/python.md
        - tools/package_manager/add/rust.md
      - Remove:
        - tools/package_manager/remove/go.md
        - tools/package_manager/remove/python.md
        - tools/package_manager/remove/rust.md
      - Import:
        - tools/package_manager/import/go.md
        - tools/package_manager/import/python.md
        - tools/package_manager/import/rust.md
    - Version Manager:
      - tools/version_manager/go.md
      - tools/version_manager/python.md
      - tools/version_manager/rust.md
  - Project Management:
    - project_management/index.md
    - Layout:
      - project_management/layout/go.md
      - project_management/layout/python.md
      - project_management/layout/rust.md
  - Data Types:
    - data_types/index.md
    - Char:
      - data_types/char/c.md
    - Int:
      - data_types/int/c.md
    - Float:
      - data_types/float/c.md
    - Enum:
      - data_types/enum/c.md
    - Array:
      - data_types/array/c.md
    - Union:
      - data_types/union/c.md
    - Struct:
      - data_types/struct/c.md
  - Data Structures:
    - data_structures/index.md
    - Tagged Union:
      - data_structures/tagged_union/c.md
    - Slice:
      - data_structures/slice/c.md
    - List:
      - data_structures/list/c.md
    - Stack:
      - data_structures/stack/c.md
    - Queue:
      - data_structures/queue/c.md
    - Hash Map:
      - data_structures/hash_map/c.md
    - Tree:
      - data_structures/tree/c.md
  - How to work with X:
    - how_to_work_with_x/index.md
    - Print & Scan:
      - how_to_work_with_x/print_scan/c.md
      - how_to_work_with_x/print_scan/go.md
      - how_to_work_with_x/print_scan/python.md
      - how_to_work_with_x/print_scan/rust.md
    - File:
      - how_to_work_with_x/file/go.md
      - how_to_work_with_x/file/python.md
      - how_to_work_with_x/file/rust.md
    - Directory:
      - how_to_work_with_x/directory/go.md
      - how_to_work_with_x/directory/python.md
      - how_to_work_with_x/directory/rust.md
    - Process:
      - how_to_work_with_x/process/go.md
      - how_to_work_with_x/process/python.md
      - how_to_work_with_x/process/rust.md
    - Thread:
      - how_to_work_with_x/thread/go.md
      - how_to_work_with_x/thread/python.md
      - how_to_work_with_x/thread/rust.md
    - Network:
      - how_to_work_with_x/network/go.md
      - how_to_work_with_x/network/python.md
      - how_to_work_with_x/network/rust.md
    - Log:
      - how_to_work_with_x/log/c.md
      - how_to_work_with_x/log/go.md
      - how_to_work_with_x/log/python.md
      - how_to_work_with_x/log/rust.md
    - File Lock:
      - how_to_work_with_x/file_lock/c.md
      - how_to_work_with_x/file_lock/go.md
      - how_to_work_with_x/file_lock/python.md
      - how_to_work_with_x/file_lock/rust.md
