site_name: Learning Programming Languages
site_url: https://127.0.0.1
theme:
  name: material
  palette:
    primary: green
  features:
    - content.tooltips

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Install:
    - install/go.md
    - install/javascript.md
    - install/python.md
    - install/rust.md
  - Tools:
    - tools/index.md
    - Compile:
      - tools/compile/go.md
      - tools/compile/javascript.md
      - tools/compile/python.md
      - tools/compile/rust.md
    - Format:
      - tools/format/go.md
      - tools/format/javascript.md
      - tools/format/python.md
      - tools/format/rust.md
    - Debug:
      - tools/debug/go.md
      - tools/debug/javascript.md
      - tools/debug/python.md
      - tools/debug/rust.md
    - LSP:
      - tools/lsp/go.md
      - tools/lsp/javascript.md
      - tools/lsp/python.md
      - tools/lsp/rust.md
    - Package Manager:
      - tools/package_manager/index.md
      - Initialize:
        - tools/package_manager/initialize/go.md
        - tools/package_manager/initialize/python.md
        - tools/package_manager/initialize/rust.md
      - Add:
        - tools/package_manager/add/go.md
        - tools/package_manager/add/python.md
        - tools/package_manager/add/rust.md
      - Remove:
        - tools/package_manager/remove/go.md
        - tools/package_manager/remove/python.md
        - tools/package_manager/remove/rust.md
      - Import:
        - tools/package_manager/import/go.md
        - tools/package_manager/import/python.md
        - tools/package_manager/import/rust.md
    - Version Manager:
      - tools/version_manager/go.md
      - tools/version_manager/python.md
      - tools/version_manager/rust.md
  - Project Management:
    - project_management/index.md
    - Layout:
      - project_management/layout/go.md
      - project_management/layout/python.md
      - project_management/layout/rust.md
  - How to work with X:
    - how_to_work_with_x/index.md
    - Files:
      - how_to_work_with_x/files/go.md
      - how_to_work_with_x/files/python.md
      - how_to_work_with_x/files/rust.md
    - Directories:
      - how_to_work_with_x/directories/go.md
      - how_to_work_with_x/directories/python.md
      - how_to_work_with_x/directories/rust.md
