site_name: Learning Programming Languages
site_url: https://127.0.0.1
theme:
  name: material
  palette:
    primary: green
  features:
    - content.tabs.link

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Installing:
    - installing/go.md
    - installing/python.md
    - installing/rust.md
  - Tooling:
    - tooling/index.md
    - Compiling:
      - tooling/compiling/go.md
      - tooling/compiling/python.md
      - tooling/compiling/rust.md
    - Formatting:
      - tooling/formatting/go.md
      - tooling/formatting/python.md
      - tooling/formatting/rust.md
    - Debugging:
      - tooling/debugging/go.md
      - tooling/debugging/python.md
      - tooling/debugging/rust.md
    - Package Manager:
      - tooling/package_manager/go.md
      - tooling/package_manager/python.md
      - tooling/package_manager/rust.md