site_name: Learning Programming Languages
site_url: https://127.0.0.1
theme:
  name: material
  palette:
    primary: green
  features:
    - content.tabs.link
    - content.tooltips

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Introduction: index.md
  - Install:
    - install/go.md
    - install/python.md
    - install/rust.md
  - Tools:
    - tools/index.md
    - Compile:
      - tools/compile/go.md
      - tools/compile/python.md
      - tools/compile/rust.md
    - Format:
      - tools/format/go.md
      - tools/format/python.md
      - tools/format/rust.md
    - Debug:
      - tools/debug/go.md
      - tools/debug/python.md
      - tools/debug/rust.md
    - Package Manager:
      - tools/package_manager/go.md
      - tools/package_manager/python.md
      - tools/package_manager/rust.md
  - Project Management:
    - project_management/index.md
    - Layout:
      - project_management/layout/go.md
      - project_management/layout/python.md
      - project_management/layout/rust.md
    - Package, Library, Module:
      - project_management/package/go.md
      - project_management/package/python.md
      - project_management/package/rust.md